name: CI2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 30s
  success:
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - name: success
        run: echo sucessssssccs
