name: CI2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: fails
        run: exit 1

  success:
    runs-on: ubuntu-latest
    needs: [prep]
    steps:
      - name: success
        run: echo sucessssssccs
