name: CI
on:
  push:
    branches:
      - main
      - actions-test
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      VERCEL_PROJECTS: ${{ steps.vercel_projects.outputs.VERCEL_PROJECTS }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: yarn install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v2
      - name: Prepare build targets
        id: vercel_projects
        run: |
          PROJECTS=$(npx nx print-affected --target=vercel --select=tasks.target.project)
          if [[ $PROJECTS != "[]" ]]; then
            echo "::set-output name=VERCEL_PROJECTS::[$PROJECTS]"
            echo $PROJECTS
          fi
      - name: echo
        id: echo
        run: echo ${{steps.vercel_projects.outputs.VERCEL_PROJECTS}}
  main:
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix: ${{ needs.prepare.outputs.VERCEL_PROJECTS }}
    steps:
      - run: echo ${{needs.prepare.outputs.VERCEL_PROJECTS}}
