name: Vercel manual deploy
on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Vercel project'
        required: true
        type: choice
        options:
        - WEB1
        - WEB2
      vercel-env:
        description: 'Vercel enviroment'
        required: true
        default: preview
        type: choice
        options:
        - preview
        - production

jobs:
  vercel-deploy-preview:
    if: inputs.vercel-env == preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: false
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets[format('{0}_VERCEL_PROJECT_ID', inputs.project)] }}
  vercel-deploy-prod:
    if: inputs.vercel-env == production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-comment: false
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets[format('{0}_VERCEL_PROJECT_ID', inputs.project)] }}
          vercel-args: --prod
    env:
      PROJECT: ${{ inputs.project }}

