on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  echo_pr_number:
    if: github.event.pull_request.state != 'closed' || (github.event.pull_request.merged && github.ref == 'refs/heads/main' )
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          echo "Pull Request Number: $PR_NUMBER"
  if_merged:
    if: github.event.pull_request.merged && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          echo "Pull Request Number: $PR_NUMBER"
  should_run_on_merge:
    needs: echo_pr_number
    if: github.event.pull_request.merged && github.ref == 'refs/heads/main' && always()
    runs-on: ubuntu-latest
    steps:
      - name: checkout2
        uses: actions/checkout@v3
