on:
  pull_request:
    types:
      - closed
  push:
    branches: main

jobs:
  echo_pr_number:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          echo "Pull Request Number: $PR_NUMBER"
  if_merged:
    if: github.event.pull_request.merged && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          echo "Pull Request Number: $PR_NUMBER"
