on:
  pull_request:
    types:
      - closed
  push:
    branches: main

jobs:
  echo_pr_number:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          echo "Pull Request Number: $PR_NUMBER"
      - run: |
          echo with gh
          echo $(gh pr view --json number -q .number || echo "")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          echo "Pull Request Number: $PR_NUMBER"
      - run: |
          echo on merged
          echo $(gh pr view --json number -q .number || echo "")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  on_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          echo "Pull Request Number: $PR_NUMBER"
      - run: |
          echo On push
          echo $(gh pr view --json number -q .number || echo "")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
